site_name: "2022 SANS HHC Write-Up"
site_author: Thomas Bouve
site_url: https://n00.be/HolidayHackChallenge2022/
copyright: Copyright &copy; 2022 <a href="https://n00.be">Thomas Bouve</a>
theme:
  icon:
    # logo: fontawesome/regular/snowflake
    # logo: fontawesome/solid/sleigh
    # logo: fontawesome/solid/tree
    logo: fontawesome/solid/candy-cane
    # logo: material/rocket-launch
  name: material
  favicon: img/misc/favicon.ico
  features:
    #- navigation.instant
    - toc.integrate
    #- navigation.top
    #- navigation.tabs
    #- navigation.tabs.sticky
    #- navigation.sections
    #- navigation.expand
  palette:
    scheme: default
    primary: teal
    accent: teal
extra:
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/crahan
      name: CraHan on Twitter
    - icon: fontawesome/brands/github
      link: https://github.com/crahan
      name: CraHan on GitHub
    - icon: fontawesome/brands/instagram
      link: https://www.instagram.com/crahan/
      name: CraHan on Instagram
extra_css:
  - css/extra.css
extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/tablesort/5.2.1/tablesort.min.js
  - js/tablesort.js
markdown_extensions:
  - abbr
  - attr_list
  - admonition
  - meta
  - footnotes
  - def_list
  - toc:
      permalink: ⚓︎
      toc_depth: 2
  - pymdownx.details
  - pymdownx.keys
  - pymdownx.details
  - pymdownx.tabbed
  - pymdownx.superfences
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.tasklist:
      custom_checkbox: true
nav:
- Welcome: 'index.md'
- Objectives:
  - KringleCon Orientation: 'objectives/o1.md'
  - Wireshark Practice: 'objectives/o2.md'
  - Windows Event Logs: 'objectives/o3.md'
  - Suricata Regatta: 'objectives/o4.md'
  - Clone with a Difference: 'objectives/o5.md'
  - Prison Escape: 'objectives/o6.md'
  - Jolly CI/CD: 'objectives/o7.md'
  - Boria PCAP Mining: 'objectives/o8.md'
  - Open Boria Mine Door: 'objectives/o9.md'
  - Glamtariel's Fountain: 'objectives/o10.md'
  - AWS CLI Intro: 'objectives/o11.md'
  - Trufflehog Search: 'objectives/o12.md'
  - Exploitation via AWS CLI: 'objectives/o13.md'
  - Buy a Hat: 'objectives/o14.md'
  - Blockchain Divination: 'objectives/o15.md'
  - Exploit a Smart Contract: 'objectives/o16.md'
- Easter Eggs: 'easter_eggs.md'
